### ISSUE TITLE
Support for additional node flags like --loader

### ISSUE THREAD

**Issue by Magoli1** [connor4312/nodejs-testing#10]
Hey 😀 

I am wondering if there is any option to provide additional node flags like `--loader` to this plugin? In my case, I usually use something like `node --loader esmock [...]` to start my tests. Any hint is highly appreciated!

Cheers 🚀 
Robert

**Comment by Magoli1** [comment]
Kinda related: https://github.com/connor4312/nodejs-testing/issues/4

**Comment by daKmoR** [comment]
I think this could be solved by adding an additional setting and then passing that along to 

https://github.com/connor4312/nodejs-testing/blob/17a5620b44e4a250a5d24f49c7e429581cc4d17e/src/runner.ts#L190

The options could be named `nodejsParams` and would be similar to the existing `nodejs-testing.include`.

probably supporting the `launch` variable like `${workspaceFolder}` would make sense so you could then set it like so

nodejsParams Array:

1. `--import`
2. `${workspaceFolder}/my-file.js`
3.  `--loader`
4. `esmock`

and then we could just pass it along to the `spawn`

such a feature would solve this and #8

@connor4312 shall I prepare a Pull Request for this feature?

**Comment by connor4312** [comment]
Sure, I'd be happy to take a PR, just haven't had a lot of time to work on this recently.

**Comment by daKmoR** [comment]
nice - I will start working on it 👍

**Comment by connor4312** [comment]
Published in 1.1.0
