### ISSUE TITLE
Test are not being recognized

### ISSUE THREAD

**Issue by raigorx** [connor4312/nodejs-testing#11]
I have main.test.js in my root directory, and is not being show.

<img width="197" alt="image" src="https://github.com/connor4312/nodejs-testing/assets/10247765/9ba49f56-102c-4a64-8206-81fc4de331a3">

Any way to get logs or a kind of debug info?

**Comment by connor4312** [comment]
Can you share a .zip of your project so I can try this locally?

**Comment by raigorx** [comment]
https://github.com/raigorx/Simple-Text-Editor

Maybe it's ESM the culprit

**Comment by koistya** [comment]
I'm also using ESM, the list of tests shows up OK in the test eplorer, but when I try to run them, it fails with:

```
worker1> starting /Users/User/Projects/example/example.test.js
worker1> 1..0 # no tests found
```

**Comment by uwinkelvos** [comment]
Although the [tests say it should not be a problem](https://github.com/connor4312/nodejs-testing/blob/main/src/parsing.test.ts), there seems to be a issue with recognizing `import test from 'node:test'`. see example above and also [here](https://github.com/uwinkelvos/connor4312.nodejs-testing-test/blob/main/src/default.test%20.ts).

**Comment by connor4312** [comment]
In recent versions we use a more reliable way to report+read test results, please let me know if you continue to experience issues.
