### ISSUE TITLE
Test-Explorer displays 0/0 tests 

### ISSUE THREAD

**Issue by jngross95** [connor4312/nodejs-testing#14]
If I start the Tests at file-level or directory level in VS-Code Testexplorer, then the UI displays 0/0 tests passed.

![image](https://github.com/connor4312/nodejs-testing/assets/67872991/57d862d3-258c-42ca-b09b-687c1371f11f)

However, the tests are executed correctly internally. Die Interface does not update.  

It's probably because the  Array 'next.include' ist empty.

**Comment by jngross95** [comment]
my VSCode Version:

![image](https://github.com/connor4312/nodejs-testing/assets/67872991/9c468034-bee5-4289-b501-13b93f480039)

**Comment by connor4312** [comment]
In recent versions we use a more reliably way to report+read test output, please let me know if you continue to experience this.
