### ISSUE TITLE
Multi-Root Workspace Test Discovery not Working

### ISSUE THREAD

**Issue by NoelAbrahams** [connor4312/nodejs-testing#15]
Hi

Given a set up like the following:

Workspace Settings JSON
```tsconfig
    "folders": [
        {
            "path": "aaa"
        },
        {
            "path": "bbb"
        },
        {
            "path": "ccc"
             // This contains hello.test.js
        },
  ]
```

We want to limit test discovery to folder 'ccc'. A setting like the following

```json
"nodejs-testing.include": ["ccc"]
```

does not discover hello.test.js.  Changing to `"nodejs-testing.include": ["./"]` does work, but that's not what we want.

**Comment by connor4312** [comment]
In the latest release, I've added support for the `${workspaceFolder:name}` variable. Relative patterns are applied to all workspaces, but you can use absolute paths in specific workspace folders. For example:

```
"nodejs-testing.include": [
	// includes myTests in workspace folderA
	"${workspaceFolder:folderA}/myTests",
	// includes allTests in all workspace folders
	"allTests"
]
```

**Comment by NoelAbrahams** [comment]
It's working as expected after the update. Thanks.
