### ISSUE TITLE
Do not automatically switch over to the Test Results pane

### ISSUE THREAD

**Issue by NoelAbrahams** [connor4312/nodejs-testing#18]
The UX here is a bit of a problem. The scenario is when we have a TypeScript compiler watcher running on the Terminal pane.

So the workflow goes something like this:

* Assume a test is broken.
* Fix the test case and save the file.
* I'm currently monitoring the Terminal pane for errors.

![image](https://github.com/connor4312/nodejs-testing/assets/1106823/6331dad8-4f22-4271-b2b3-9a428401b3d8)

* Hit run on the test.
* This switches over to the Test Results pane.
* I edit the test case to make further changes and save the file.
* I now need to switch over to the Terminal Pane to see if there are any compiler errors.

I don't see a huge benefit in the info that is printed out on the Test Results pane, since the test explorer already shows things clearly enough.

Perhaps this could be configurable? eg `showResultsPaneOnCompletion`.

**Comment by connor4312** [comment]
This is configurable with the testing.useTesting setting in VS Code

**Comment by NoelAbrahams** [comment]
@connor4312 what's the setting again? Can't seem to be able to find it:

![image](https://github.com/connor4312/nodejs-testing/assets/1106823/e0540e06-8b41-4969-b940-492be842cf4a)

**Comment by NoelAbrahams** [comment]
Never mind. Found it. It's `testing.openTesting`. Thanks.

**Comment by connor4312** [comment]
sorry, typo'd, yep that's right
