### ISSUE TITLE
Peek on assertion failure duplicates message

### ISSUE THREAD

**Issue by NoelAbrahams** [connor4312/nodejs-testing#19]
In the image below, the message 'Expected value to be true. Actual 'false'' (which comes from the error thrown by the assertion library) is repeated:

![image](https://github.com/connor4312/nodejs-testing/assets/1106823/a501a9cb-ed28-4714-a339-cef212c3ce64)

A suggested improvement could be the following:
![image](https://github.com/connor4312/nodejs-testing/assets/1106823/b2ffbfdf-ea92-41aa-8721-3e7b03e0cebd)

**Comment by connor4312** [comment]
This is just the design of VS Code -- the title of the peek is the first line of the error message.
