### ISSUE TITLE
File system errors are not properly failing tests

### ISSUE THREAD

**Issue by skanaar** [connor4312/nodejs-testing#2]
If I try to load a missing file in a test the test is not registered as neither passed nor failed.
In the test explorer that test is still marked with a grey circle. But I can confirm that an error is thrown by the fs.readFileSync function.

But throwing a `new Error('bla')` error properly fails the test.

<img width="769" alt="Screenshot 2023-02-25 at 14 17 03" src="https://user-images.githubusercontent.com/641015/221359039-12c365ad-4bd0-4050-8c3e-a4a312a178d1.png">

**Comment by connor4312** [comment]
Thanks for the issue, I just published 1.0.1 with the fix. (May take a minute to appear on the marketplace)
