### ISSUE TITLE
run only single test

### ISSUE THREAD

**Issue by cdaringe** [connor4312/nodejs-testing#21]
# Problem

I attempt to run a single test, but all tests are run.

# Discussion

- single tests can be run: https://nodejs.org/api/test.html#filtering-tests-by-name

# Demo

single test clicked in test explorer, all tests run:

<img width="931" alt="Untitled" src="https://github.com/connor4312/nodejs-testing/assets/1003261/501f274c-8a60-433d-8950-24043c32025a">

**Comment by connor4312** [comment]
This is supported. What version of Node.js are you using?

**Comment by cdaringe** [comment]
Im on 20.8.0

**Comment by adrienjoly** [comment]
Same problem here, unfortunately.

**Comment by connor4312** [comment]
Should be fixable once https://github.com/nodejs/node/pull/51577 is released

**Comment by connor4312** [comment]
This should be fixed in the latest release if you're running Node 22.
