### ISSUE TITLE
Support ANSI colors in test failures output

### ISSUE THREAD

**Issue by rluvaton** [connor4312/nodejs-testing#27]
if an error throws that uses ANSI color it will not be colored (`expect` package for example colorize the output)

![image](https://github.com/connor4312/nodejs-testing/assets/16746759/a240d95b-cfed-4183-8a2b-079197bcee8a)

**Comment by connor4312** [comment]
Implemented upstream in https://github.com/microsoft/vscode/pull/207852

**Comment by rluvaton** [comment]
Thanks, that is even better solution!
