### ISSUE TITLE
Function without argument break test discovery

### ISSUE THREAD

**Issue by skanaar** [connor4312/nodejs-testing#3]
Weird behavior where a function invocation without arguments break test discovery.

```
const { test } = require('node:test')

test('function without argument break test discovery', function () {
  foo()
})
```

**Comment by connor4312** [comment]
1.0.2 is published with the fix

**Comment by skanaar** [comment]
I am impressed by the speed at which these fixes roll in! Good job 😄

**Comment by connor4312** [comment]
Having nice and succinct issues with repro steps makes it easy, thank you 🙂
