### ISSUE TITLE
Is there a way to run tests from project directory?

### ISSUE THREAD

**Issue by Niakr1s** [connor4312/nodejs-testing#32]
Hello! Thanks for your extension!

I have a problem. I have test data in '{project_dir}/testdata' folder, and I want them to load it from filesystem in tests. But it seems that Test Explorer runs tests with cwd set to test file' directory.

For example, if I try to do this in file 'tests/foo/bar.test.js':
```js
let raw = readFileSync('./testdata/raw.json', 'utf-8');
```
I'm getting cryptic window with message: 'The editor could not be opened because the file was not found.' Command 'node --test' from terminal, if I run it from project directory, works great though.

However, if I change filepath to relative:
```js
let raw = readFileSync('../../testdata/raw.json', 'utf-8');
```
it works smoothly.

I made a small investigation: command process.cwd(), executed in a debug console, gets me directory of a test file. In comparison, same command when I run tests with jest, results in the project directory.

So, is it possible to fix it so that tests always run from project directory?

**Comment by Niakr1s** [comment]
I ended up in writing small helper function to find workspace dir, so maybe it could be helpful for someone, feel free to use!
```js
/**
 * Searches for the package.json in the parent directories
 * @returns {string} - The path to the workspace, where the package.json is
 */
export function getWorkspaceDir () {
  const PACKAGE_JSON = 'package.json';

  function searchInParents (dir, wanted) {
    const items = readdirSync(dir);
    if (items.some(item => item === wanted)) {
      return dir;
    } else {
      return searchInParents(path.dirname(dir), wanted);
    }
  }
  return searchInParents(process.cwd(), PACKAGE_JSON);
}
```

**Comment by connor4312** [comment]
Yea, I agree that tweaking this makes sense. I will probably have some "projectRoot" setting, defaulting to your workspace folder), hat controls the cwd among other things (things that we naively root at the workspace folder today)

**Comment by Niakr1s** [comment]
That would've been great!

**Comment by techfg** [comment]
Great extension, thank you for your work!

Running in to this same issue - tests are all written assuming execution from projectRoot and fail when using test runner.  Current workaround is:

`settings.json`
```json
{
    "nodejs-testing.pretest": [
        "./test-prep.sh"
    ]
}
```
`test-prep.sh`
```bash
cd ..
```

**Comment by techfg** [comment]
ty @connor4312!!
