### ISSUE TITLE
pretest setting not working

### ISSUE THREAD

**Issue by justinfagnani** [connor4312/nodejs-testing#34]
I've added `["npm", "run", "pretest"]` to my preset config and package.json and am getting this error:

```
 *  Running pretest script: ["npm", "run", "pretest"] 

spawn ["npm", "run", "pretest"] ENOENT
```

This is with the verbose setting set.

I wonder if this is happening because I use nvm?

**Comment by connor4312** [comment]
This would mean that `npm` is not in your PATH, or not in the PATH variable that VS Code has. You want to ensure that VS Code inherits your variables correctly, for example by prefering to launch it from a terminal containing the environment you want.

**Comment by dvirtz** [comment]
I also see this issue on Windows and npm is in path.

**Comment by zeel01** [comment]
I'm also having this problem, `npm` is most certainly in my PATH on Windows.
