### ISSUE TITLE
Test cases not found if using CommonJS instead of ES6

### ISSUE THREAD

**Issue by Tkong1** [connor4312/nodejs-testing#42]
I am new to node:test and wanted to use the extension to execute my first node unit tests.
I am usually using CommonJS module style for my node.js projects.
But i was only able to see the tests on the Testing window in VSCode if i use the ES6 module style.

Setup:
OS: Ubuntu 22.04
VS-Code: v1.90.1
Node.js: v22.3.0
node:test runner: v1.5.1

Test file (ES6): /test/test.js
```javascript
import { test } from "node:test";

test("will pass", () => {
  console.log("hello world");
});

test("will fail", () => {
  throw new Error("fail");
});
```
![2024-06-17 21-00-55](https://github.com/connor4312/nodejs-testing/assets/38532195/e6c891be-b1b0-4939-8276-2905dc11aef3)

Test file (CommonJS): test/test.js
```javascript
const test = require('node:test');

test("will pass", () => {
  console.log("hello world");
});

test("will fail", () => {
  throw new Error("fail");
});
```
![2024-06-17 20-59-01](https://github.com/connor4312/nodejs-testing/assets/38532195/638c18be-e10a-421e-843b-df1f18fcfee3)

When i run the node:test's with the CLI it works with CommonJS module style.

![2024-06-17 21-05-48](https://github.com/connor4312/nodejs-testing/assets/38532195/9d31b33f-d672-4f91-b072-54145bc89246)

**Comment by connor4312** [comment]
You want to change

```
const test = require('node:test');
```

to

```
const { test } = require('node:test');
```

**Comment by Tkong1** [comment]
Thanks a lot for this tip, this works.
Even if i don't really know what the issue with
`const test = require('node:test');` 
is.

**Comment by connor4312** [comment]
We don't handle that case, I didn't know they default-export the `test` function. I'll add support for that.
