### ISSUE TITLE
cwd should be the workspace folder not the folder with the tests.

### ISSUE THREAD

**Issue by vsDizzy** [connor4312/nodejs-testing#43]
Current working directory should not be changed. It should work exactly as `node --test` does.
You can add a test with `console.log(process.cwd())` and see the difference.

This affects many things, e.g. relative path to the sqlite db defined in model.ts is wrongly resolved when I run tests.

**Comment by connor4312** [comment]
I think this duplicates https://github.com/connor4312/nodejs-testing/issues/32
