### ISSUE TITLE
Recoginize bare test import

### ISSUE THREAD

**Issue by hildjj** [connor4312/nodejs-testing#45]
This should be a valid test:

```js
import test from 'node:test'
test('foo', () => {})
```

however, to get this to be recognized by the plugin in my project, I had to do this:

```js
import {test} from 'node:test'
test('foo', () => {})
```

I figured this out looking at #11 and #23.

**Comment by connor4312** [comment]
Duplicates https://github.com/connor4312/nodejs-testing/issues/42
