### ISSUE TITLE
Test counts are confusing

### ISSUE THREAD

**Issue by BryanHuntNV** [connor4312/nodejs-testing#47]
The test counts reported include the describe hierarchy and are somewhat confusing.  For example if I have an `it` in a 6 deep hierarchical `describe`, the extension will report there are 7 tests when there is really only 1 test.

**Comment by connor4312** [comment]
This is a thing in VS Code.

VS Code counts all tests in the tree, including intermediate nodes. Maybe it would be better to count leaf nodes, but that still gives a slightly surprising count when dealing with subtests or parameterized tests.
