### ISSUE TITLE
When using test() inside describe(), trying to run a single test results in the whole describe() being ran

### ISSUE THREAD

**Issue by 9600bauds** [connor4312/nodejs-testing#49]
Let's say I have three different describe blocks, like this:
![image](https://github.com/user-attachments/assets/27c60491-acf2-4616-ad89-b401b784a154)
And I click the "Run Test" button next to test C3 (the 3rd test of describe block C).

What I expected to happen:
All tests except C3 are skipped

What actually happened:
![image](https://github.com/user-attachments/assets/b68019c6-a258-4a57-965b-b83de50d247a)
All tests inside describe block C are ran.
This is annoying because tests C1 and C2 might be slow or produce testing messages.
Furthermore, the other describe blocks are shown as passing, even though the tests inside them *are* skipped, which is confusing but not that bad.

**Comment by connor4312** [comment]
Thanks for the issue, what version of Node.js are you using?

**Comment by 9600bauds** [comment]
Apologies for not including that info in the OP, I am running node v20.11.0

**Comment by connor4312** [comment]
Please update to Node 22. Versions below that did not have very good filtering logic https://github.com/nodejs/node/issues/46728.

**Comment by 9600bauds** [comment]
Thank you, that does work a lot better. Good luck!
