### ISSUE TITLE
node:assert functions not properly failing tests

### ISSUE THREAD

**Issue by skanaar** [connor4312/nodejs-testing#5]
Using the assert methods from `node:assert` does not properly fail a test.
Instead a toast with this message pops up:

`Worker executed with code 1: /Users/kallin/.vscode/extensions/connor4312.nodejs-testing-1.0.2/out/runner-worker.js:206`

But explicitly throwing an Error properly fails the test.

**VS Code: 1.76.1**
**nodejs-testing: v1.0.2**

**Sample test file**

```
import { test } from 'node:test'
import { deepEqual } from 'node:assert'

test('should pass', () => {
  deepEqual({ foo: 'bar' }, { foo: 'bar' })
})

test('will fail properly', () => {
  throw new Error('fail')
})

test('will not fail properly', () => {
  deepEqual({ foo: 'bar' }, { foo: 'x' })
})
```

**State of my editor**
<img width="844" alt="Screenshot 2023-03-12 at 19 16 35" src="https://user-images.githubusercontent.com/641015/224564968-d236affe-10a3-4beb-8cc2-d05e33417d9b.png">

**Comment by connor4312** [comment]
Unfortunately this is a Node.js bug: https://github.com/nodejs/node/issues/47075

**Comment by skanaar** [comment]
Oh! 😨 
Nice bug report in Node, looks like they are addressing it.
