### ISSUE TITLE
[Meta] Missing Github releases/changelog for some versions.

### ISSUE THREAD

**Issue by zeel01** [connor4312/nodejs-testing#56]
Previously I had v1.5.2 installed from the extensions marketplace, but there is no tag, release, or commit for v1.5.2 that I can see. Today the extension updated to v1.6.0 and I do see a commit changing that version, but there isn't a tag or release associated with it. The marketplace also lists a v1.5.3 existed as well. It would be nice to have a change log or at least a tag for each update that gets pushed so users can tell what is changing.

I generally don't auto-update, since I've had extensions randomly break on me before, so when deciding to manually update it's a little hard if I don't know if there's a change that impacts me or not.

**Comment by connor4312** [comment]
Added the missing releases
