### ISSUE TITLE
Ignore files when debugging tests.

### ISSUE THREAD

**Issue by zeel01** [connor4312/nodejs-testing#57]
Normally when running the debugger the `launch.json` file can be used to control various settings including `skipFiles` which allows us to, among other things, ignore files in `node_modules`. However it doesn't appear that the test running uses any of the profiles from the `launch.json` (if I delete the file, the test runner happily starts a debugging sessions anyway). As such, there doesn't appear to be a way to configure it so the debugger will skip certain files?

It would nice if this were an option (or if it's already possible, it would be great if there was a note in the readme). Generally it would be cool if we configure all the usual debugging options, but ignoring code we didn't write is the most important one imo.

**Comment by coder-mike** [comment]
I have the same problem. I like to debug with "Caught Exceptions" breakpoints enabled, but this requires excluding certain folders from the debugger because certain libraries like to throw exceptions as a matter of normal operation.
